import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {Providers} from "../components/providers";

import "./globals.css";
import TopNavbar from "@/components/navbar/TopNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNavbar />
          <main className=" container mx-auto p-10">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
